[package]
name = "wx-js-sdk"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
snafu = "0.8.2"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"

